[build]
base="AirbnbDashboard-finalproject"
  command = "npm run build:prod"
  publish = "dist/browser"
  command = "npm run build:prod"
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200